version: "3.7"
services:
  db:
    image: postgres
    container_name: db
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=acwhaledb
    volumes:
      - ./volumes/data/db:/var/lib/postgresql/data
    ports:
      - 5432:5432

  api:
    build: ./AcBackend
    container_name: "api"
    image: "aspnetapp"
    ports:
      - 5001:80
    depends_on:
      - db

  web:
    build:
      context: ./ac-frontend
      dockerfile: Dockerfile
    container_name: web
    ports:
      - 3000:3000
    depends_on:
      - api
    stdin_open: true
