version: "3.7"
services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=acwhaledb
    volumes:
      - ./volumes/data/db:/var/lib/postgresql/data
    ports:
      - 5432:5432
